Driver entity crud
MotyaMiracle/YMS pull request #6
Opened 2023-02-22 14:51 UTC by MotyaMiracle

Переделал и добавил AutoMapped

2023-02-24 14:20 UTC, Apx2100 requested changes

2023-02-24 14:20 UTC, Apx2100 commented on Yard_Management_System/CRUDs/Driver/CreateDriver.cs
> +        [Required]
Раздели свойства между собой для удобства чтения

2023-02-24 14:20 UTC, Apx2100 commented on Yard_Management_System/CRUDs/Driver/CreateDriver.cs
> +        [Required]
И добавь summary с описанием полей

2023-02-24 14:20 UTC, Apx2100 commented on Yard_Management_System/Controllers/DriversController.cs
> +        {
Сделай сервис для работы с водителями и вынеси всю логику туда, маппить сущности нужно тоже внутри сервиса, в API мы только обращаемся к сервису с помощью интерфейса

2023-02-24 14:23 UTC, Apx2100 commented on Yard_Management_System/Controllers/DriversController.cs
> +        {
в GET запросе возвращать нужно её же а не модель которая лежит в БД

2023-02-25 12:48 UTC, MotyaMiracle commented on Yard_Management_System/Services/Drivers/DriverService.cs
> +        public async Task<List<Driver>> GetAllAsync(CancellationToken token)
Тут не знаю как правильно реализовать, чтобы возвращало не модель из БД, а DriverDto, при этом используя AutoMapped

2023-02-28 07:54 UTC, Apx2100 requested changes

2023-02-28 07:54 UTC, Apx2100 commented on Yard_Management_System/Services/Drivers/DriverDto.cs
> +        public Guid Id { get; set; }
Сделай строкой

2023-02-28 07:54 UTC, Apx2100 commented on Yard_Management_System/Services/Drivers/DriverService.cs
> +            if (driverDto.Id == new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"))
Поменяй костыльную проверку на if(!string.IsNullOrWhiteSpace(driverDto.Id))

2023-02-28 07:54 UTC, Apx2100 commented on Yard_Management_System/Services/Drivers/DriverService.cs
> +                Entries = drivers.Select(d => new DriverDto
Используй AutoMapper

2023-03-01 12:35 UTC, merged