Storage entity crud
MotyaMiracle/YMS pull request #7
Opened 2023-02-22 14:52 UTC by MotyaMiracle

Переделал и добавил AutoMapped

2023-02-24 14:23 UTC, Apx2100 requested changes

2023-02-24 14:23 UTC, Apx2100 commented on Yard_Management_System/Controllers/StorageController.cs
> +        {
Сделай сервис для работы со складами и вынеси всю логику туда, маппить сущности нужно тоже внутри сервиса, в API мы только обращаемся к сервису с помощью интерфейса

2023-02-24 14:23 UTC, Apx2100 commented on Yard_Management_System/CRUDs/Storage/CreateStorage.cs
> +    public class CreateStorage
Переименуй модель в StorageDto и в GET запросе возвращать нужно её же а не модель которая лежит в БД

2023-02-25 11:51 UTC, MotyaMiracle commented on Yard_Management_System/Services/Storages/StorageService.cs
> +        public async Task<List<Storage>> GetAllAsync(CancellationToken token)
Тут не знаю как правильно реализовать, чтобы возвращало не модель из БД, а StorageDto, при этом используя AutoMapped

2023-02-26 08:51 UTC, MotyaMiracle commented on Yard_Management_System/Services/Storages/StorageService.cs
> +        public async Task<StorageEntriesDto> GetAllAsync(CancellationToken token)
Переделал, но с маппером не знаю как сделать

2023-02-28 07:56 UTC, Apx2100 requested changes

2023-02-28 07:56 UTC, Apx2100 commented on Yard_Management_System/Services/Storages/StorageDto.cs
> +        public Guid Id { get; set; }
Сделай строкой

2023-02-28 07:56 UTC, Apx2100 commented on Yard_Management_System/Services/Storages/StorageService.cs
> +            if (storageDto.Id == new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"))
Поменяй костыльную проверку на if(!string.IsNullOrWhiteSpace(storageDto.Id))

2023-02-28 07:56 UTC, Apx2100 commented on Yard_Management_System/Services/Storages/StorageService.cs
> +                Entries = storages.Select(s => new StorageDto
Используй AutoMapper

2023-03-01 12:48 UTC, merged